version: '3.8'

services:
  # 1. Central PostgreSQL Database
  postgres_db:
    image: postgres:15-alpine
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metadata
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 

  # 2. NGINX Load Balancer
  nginx_lb:
    image: nginx:alpine
    container_name: local_nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/master_nginx.conf:/etc/nginx/nginx.conf:ro # Mount config file as Read-Only
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow NGINX to talk to laptop's ip address
    depends_on:
      - postgres_db # Ensure database starts before the load balancer

volumes:
  pgdata: